image:
  repository: artifactory.dagility.com/docker/testtest-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: testtest-backend-habitat-test3.dagility.com
    paths:
    - /
serviceAccount:
  create: false
